// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdz6LpfPIrAitXUOs3-Zytm4XgTXjSfTo',
    appId: '1:123778616059:web:2a555e08c2951f4ad37e5e',
    messagingSenderId: '123778616059',
    projectId: 'asicity-67d74',
    authDomain: 'asicity-67d74.firebaseapp.com',
    storageBucket: 'asicity-67d74.firebasestorage.app',
    measurementId: 'G-TTL4XLCWDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwG14_tQSzht-f3XpvxqPL8yD5TNlpKR0',
    appId: '1:123778616059:android:e2addae6a3f1f1c4d37e5e',
    messagingSenderId: '123778616059',
    projectId: 'asicity-67d74',
    storageBucket: 'asicity-67d74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnEFO5g4A36Ra6ZrhobtdayputBxSMLLc',
    appId: '1:123778616059:ios:8ee64e95c1e59a43d37e5e',
    messagingSenderId: '123778616059',
    projectId: 'asicity-67d74',
    storageBucket: 'asicity-67d74.firebasestorage.app',
    iosBundleId: 'com.example.asicity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnEFO5g4A36Ra6ZrhobtdayputBxSMLLc',
    appId: '1:123778616059:ios:8ee64e95c1e59a43d37e5e',
    messagingSenderId: '123778616059',
    projectId: 'asicity-67d74',
    storageBucket: 'asicity-67d74.firebasestorage.app',
    iosBundleId: 'com.example.asicity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdz6LpfPIrAitXUOs3-Zytm4XgTXjSfTo',
    appId: '1:123778616059:web:7bf05f21b365e58dd37e5e',
    messagingSenderId: '123778616059',
    projectId: 'asicity-67d74',
    authDomain: 'asicity-67d74.firebaseapp.com',
    storageBucket: 'asicity-67d74.firebasestorage.app',
    measurementId: 'G-898HYPDT8S',
  );
}
